# Based on https://gitlab.fi.muni.cz/unix/examples/ci-examples/-/blob/java-maven/.gitlab-ci.yml
image: maven:3-jdk-11

build:
  tags:
    - shared-fi
  script:
    - mvn dependency:resolve --quiet
    - mvn package
